# deploying to server
# ansible-playbook -i <host>, playbook.yml
- hosts: all
  tasks:
    - name: copy qbittorrent script
      copy:
        src: qbittorrent-postprocess
        dest: /srv/pv/scripts/qbittorrent-postprocess
        backup: true
      tags: deploy

    - name: copy partials
      copy:
        src: "partials"
        dest: "/srv/pv/scripts/partials"
        backup: true
      tags: deploy

    - name: template files out to destination
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/srv/pv/scripts/{{ item | basename | splitext | first }}"
        backup: true
      vars:
        scriptDir: "/scripts"
      loop: "{{ lookup('fileglob', '*.groovy.j2', wantlist=True) }}"
      tags: deploy
